import { t } from 'configs/i18next';

export enum APIErrorCode {
  no_permission = 'no_permission',
  login_fail_or_block = 'Login_fail_or_block',
  verify_failed = 'verify_failed',
  device_reboot = 'device_reboot',
  device_upgrade = 'device_upgrade',
  param_error = 'param_error',
  set_config_failed = 'set_config_failed',
  get_config_failed = 'get_config_failed',
  user_blocked = 'user_blocked',
  no_support = 'no_support',
  first_login = 'first_login',
  default_failed = 'default_failed',
  token_invalid = 'token_invalid',
  device_busy = 'device_busy',
  user_expired_login = 'user_expired_login',
  data_saving_busy = 'data_saving_busy',
  function_busy = 'function_busy',
  login_at_other = 'login_at_other',
  no_heartbeat = 'no_heartbeat',
  reach_login = 'reach_login',
  black_ip = 'black_ip',
  verify_fail = 'verify_fail',
  search_failed = 'search_failed',
  device_play_locked = 'device_play_locked',
  session_invalid = 'session_invalid',
  method_not_allowed = 'method_not_allowed',
  payload_too_large = 'payload_too_large',
  uri_too_long = 'uri_too_long',
  no_need_upgrade = 'no_need_upgrade',
  forbidden = '403',
  request_timeout = 'request_timeout',
  request_re_login = 'request_re_login',
  scan_wifi_fail = 'scan_wifi_fail',
  connect_wifi_fail = 'connect_wifi_fail',
  cannot_connect_to_wifi = 'cannot_connect_to_wifi',
  unstable_network = 'unstable_network',
  internal_server_error = 'internal_server_error',
  can_not_fetch_data = 'can_not_fetch_data',
  ai_face_update_failed = 'ai_face_update_failed',
  log_get_failed = 'log_get_failed',
  already_login = 'already_login',
}

export const errorMessageMapping: Record<APIErrorCode, string> = {
  [APIErrorCode.already_login]: t('error.already_login'),
  [APIErrorCode.no_permission]: t('error.no_permission'),
  [APIErrorCode.login_fail_or_block]: t('error.login_fail_or_block'),
  [APIErrorCode.black_ip]: t('error.black_ip'),
  [APIErrorCode.verify_failed]: t('error.verify_failed'),
  [APIErrorCode.verify_fail]: t('error.verify_fail'),
  [APIErrorCode.device_reboot]: t('error.device_reboot'),
  [APIErrorCode.user_blocked]: t('error.user_blocked'),
  [APIErrorCode.forbidden]: t('error.no_permission'),
  [APIErrorCode.request_timeout]: t('error.request_timeout'),
  [APIErrorCode.request_re_login]: t('error.request_re_login'),
  [APIErrorCode.scan_wifi_fail]: t('error.scan_wifi_fail'),
  [APIErrorCode.connect_wifi_fail]: t('error.connect_wifi_fail'),
  [APIErrorCode.cannot_connect_to_wifi]: t('error.cannot_connect_to_wifi'),
  [APIErrorCode.unstable_network]: t('error.unstable_network'),
  [APIErrorCode.internal_server_error]: t('error.internal_server_error'),
  [APIErrorCode.can_not_fetch_data]: t('error.can_not_fetch_data'),
  [APIErrorCode.ai_face_update_failed]: t('error.ai_face_update_failed'),
  [APIErrorCode.log_get_failed]: t('error.log_get_failed'),
  [APIErrorCode.device_upgrade]: t('error.device_upgrade'),
  [APIErrorCode.param_error]: t('error.param_error'),
  [APIErrorCode.set_config_failed]: t('error.set_config_failed'),
  [APIErrorCode.get_config_failed]: t('error.get_config_failed'),
  [APIErrorCode.no_support]: t('error.no_support'),
  [APIErrorCode.first_login]: t('error.first_login'),
  [APIErrorCode.default_failed]: t('error.default_failed'),
  [APIErrorCode.token_invalid]: t('error.token_invalid'),
  [APIErrorCode.device_busy]: t('error.device_busy'),
  [APIErrorCode.user_expired_login]: t('error.user_expired_login'),
  [APIErrorCode.data_saving_busy]: t('error.data_saving_busy'),
  [APIErrorCode.function_busy]: t('error.function_busy'),
  [APIErrorCode.login_at_other]: t('error.login_at_other'),
  [APIErrorCode.no_heartbeat]: t('error.no_heartbeat'),
  [APIErrorCode.reach_login]: t('error.reach_login'),
  [APIErrorCode.session_invalid]: t('error.session_invalid'),
  [APIErrorCode.method_not_allowed]: t('error.method_not_allowed'),
  [APIErrorCode.payload_too_large]: t('error.payload_too_large'),
  [APIErrorCode.uri_too_long]: t('error.uri_too_long'),
  [APIErrorCode.no_need_upgrade]: t('error.no_need_upgrade'),
  [APIErrorCode.search_failed]: t('error.search_failed'),
  [APIErrorCode.device_play_locked]: t('error.device_play_locked'),
};
